export const TASK_TYPES = [
  { label: "灌溉", value: "Irrigation", description: "滴灌：缓慢滴水至根部，节水且避免叶面潮湿。浸盆：将花盆浸入水中，通过底部孔隙吸水，适合干燥基质。" },
  { label: "排水优化", value: "DrainageImprovement", description: "垫盆：抬高花盆底部，防止积水烂根。疏通排水孔：确保花盆底部孔洞通畅。" },
  { label: "施肥", value: "Fertilization", description: "基肥：种植前混入土壤的缓释肥料（如有机肥）。追肥：生长期追加肥料（如液态肥）。叶面喷施：将稀释肥料直接喷洒叶片，快速补充养分。" },
  { label: "修剪", value: "Pruning", description: "摘心：掐去茎尖促进侧枝萌发，使株型丰满。疏枝：剪除过密枝条，改善通风透光。回缩修剪：缩短过长枝条，控制植株高度。" },
  { label: "整形", value: "Training", description: "绑扎：用支架固定茎秆，防止倒伏。牵引 ：引导藤本植物沿支架生长。" },
  { label: "施药", value: "PesticideApplication", description: "喷雾：将药剂雾化喷洒于叶面或虫害部位。灌根：药剂稀释后浇灌根部，防治土传病害。烟熏：密闭空间使用烟雾剂杀灭害虫。" },
  { label: "休眠期管理", value: "DormancyManagement", description: "控水：减少浇水频率，模拟自然休眠条件。低温春化：通过低温处理促进开花（如郁金香）。" },
  { label: "繁殖操作", value: "Propagation", description: "扦插：截取茎、叶或根插入基质中生根。嫁接：将接穗嫁接到砧木上，结合两者优势。分株：分割母株的根茎或侧芽，独立栽种。" },
  { label: "光照调控", value: "LightRegulation", description: "补光：使用人工光源（如LED植物灯）补充自然光照不足，促进光合作用。遮阴：通过遮阳网或移至阴凉处减少强光直射，防止叶片灼伤。" },
  { label: "温湿度控制", value: "Temperature&HumidityControl", description: "通风 ：保持空气流通，预防病虫害和霉菌滋生。加湿：通过喷雾、加湿器或水盘增加环境湿度，适合热带植物。降温：夏季通过遮阴、喷水或空调降低环境温度。" },
  { label: "换土/换盆", value: "Repotting", description: "盆土更新：更换旧土以补充养分，避免土壤板结。盆器升级：根据植物根系大小更换更大花盆。" },
  { label: "基质调配", value: "SubstrateFormulation", description: "配土：按比例混合泥炭、珍珠岩、腐叶土等，优化透气性和保水性。消毒灭菌：高温蒸煮或药剂处理土壤，杀灭病原体和虫卵。" },
  { label: "其它", value: "Other", description: "" },
];